### ISSUE TITLE
Padrão MVC

### ISSUE THREAD

**Issue by farnetani** [danielschmitz/vue-codigos#3]
Me diga uma coisa, ao ver a parte do Frontend notei que tipo a View do html fica dentro dos componentes .vue, isso é uma prática boa? Não fica esquisito? Não teria como separarmos isso???

**Comment by danielschmitz** [comment]
Olá,

O Evan, criador do elvui, prega justamente que o html fique junto ao código javascript, mas em tags diferentes como é o arquivo vue. Para que se tenha uma mínima organização de código, é necessário criar trabalhar com componentes que sejam independentes e minimalísticos. Dê uma olhada neste artigo: [ Aplicações com VueJS: Pensando em componentes](http://www.vuejs-brasil.com.br/aplicacoes-com-vuejs-pensando-em-componentes/) para entender melhor o processo
