### ISSUE TITLE
Jquery é realmente necessário?

### ISSUE THREAD

**Issue by farnetani** [danielschmitz/vue-codigos#4]
Notei que em alguns pontos do frontend foi utilizado o jquery ($('#productModal').modal('show')), isso realmente é necessário? Não existe nada em VueJS que fizesse esse mesmo papel do Modal? Nenhum componente por exemplo?

`newProduct(){
      this.product = {}
      $('#productModal').modal('show')
    },`

**Comment by danielschmitz** [comment]
Olá,

O próprio bootstrap necessita do jquery para abrir a janela modal. Nesse contexto, quando você está usando o Bootstrap, o jquery é necessário.

Testei com outro framework css chamado Bulma e neste nao é necessário o jQuery (mas ele não tem o método "show", o modal é aberto através de uma propriedade.
