### ISSUE TITLE
VueJS + Angular

### ISSUE THREAD

**Issue by farnetani** [danielschmitz/vue-codigos#5]
Eu poderia utilizar num projeto VueJS o Angular junto? Tipo me aproveitar de algum componente bacana que já exista em Angular? Tanto a versão 1 como a versão 2?

**Comment by danielschmitz** [comment]
Olá,

acho que isso não é possível.

**Comment by doArcanjo** [comment]
:D
 https://github.com/foxdonut/meiosis

É uma abordagem nova baseado no :  SAM/PAL   sam.js.org
