### ISSUE TITLE
Livro Vue.js Na Prática, capitulo: 5.1 Testando o acesso Ajax

### ISSUE THREAD

**Issue by JoaoOliveiraFrade** [danielschmitz/vue-codigos#7]
Bom dia, tentei ler arquivo json, diretamente do file system, conforme exemplo do livro. Mas não funciona, recebo a mensagem: 

XMLHttpRequest cannot load file:///C:/meuArquivo.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

**Comment by danielschmitz** [comment]
Olá, você precisa estar no webserver (localhost)
